INSERT INTO USER (id,name,age,des) VALUES (1,'sel',1,'dt');
INSERT INTO USER (id,name,age,des) VALUES (2,'ttk',2,'mw');
INSERT INTO USER (id,name,age,des) VALUES (3,'dcw',3,'pt');
INSERT INTO USER (id,name,age,des) VALUES (4,'wxt',4,'hs');
INSERT INTO USER (id,name,age,des) VALUES (5,'jzy',5,'lg');
INSERT INTO USER (id,name,age,des) VALUES (6,'qq',6,'yg');
INSERT INTO USER (id,name,age,des) VALUES (7,'bb',7,'yg');
INSERT INTO USER (id,name,age,des) VALUES (8,'jc',8,'fc');
INSERT INTO USER (id,name,age,des) VALUES (9,'xg',9,'dt');
